spring:
  application:
    name: isupabase
  datasource:
    url: jdbc:mysql://localhost:3306/yfwj
  # url: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?user=postgres.vxguqjxsufwgzhcnojsc&password=hOPnavWk3gZIOn6N
    #url: jdbc:postgresql://192.168.0.78:5432/app_db?user=app_user&password=password
    username: root
    password: Lian@8419
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategies.SnakeCaseStrategy
  mail:
    host: smtp.qq.com
    port: 587
    username: 1327800522@qq.com
    password: rrilnhgcfirpibbb
    test-connection: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB

mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    default-fetch-size: 1000


# must re config this
isupabase:
  auth-private-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCl7h7NDJ0Y6bNm0O4N4Q04o2mA7p7c3UgIX3/NZyrD1FN/9k7+3jhyi9k6M6YST7+FBSJ8QYHzjgIMn6y2J0j34PQBdDPlpOSGAMMHgE7b0pRiGWYirhLSB9j0k4b6aiELS5E4e2JmYkDGZK5rCQYmK9QQKyckg2a8aYI7T/XzDNsDRpt0n+WxzF8AtQ5HRxnTaYxTrSXOl3o3QgDMmw6sjsBZLHmrwlwg5lRYwMeiy0bPd7dUQTS07Q/gKS24/SZxGPRzFSScubMiRe40KEVSGMLtOaBnKxwJ9PaI1Kh5wgFMCRASH8SlSCL2P4sa0iy2zL6pgQbE7rlWuly4ybq5AgMBAAECggEAE8DnVc3cneykeOcCkBBsvINnufuuWejV/HkyA8f2ZV3Pmvo9qUXXPnu7npwrdx6bVECqPFSoHdCYGdygeQbwPuI+6jVlQD+DHRjWHvx9ZtoI5CzV5ecHQo3AnE070m/0Ax456Zl2u22S/Itb4E4wtzachlg8zrH99wwwftMkGo0J2F1GlmMZx5bxmw6ls2XxY6oaJ/MhheWJVT2TgQdE2RzYLHCkz5leJ9dHEfuVES+YHNVcdhxZ4re+kSqYChDNWY5Xsk2aBVW6AIb72bcQusj9ntZFP1cV3pQSDgHjYM64uoRBl24JMt26irMa+FEAnqAnBJaDJ53j+czXN8kUoQKBgQC3wswRPBCaa9/GkAeL8CpFd5Dq2kB8Hobp9APG+dSeIqnmc5ls8PtnsR3ISDy8Tj9j9U17jNKqmXuhDPM5H/qgLGdu5Zqn1YB+m5R4He7A3goKNHRoOOnd5ryYwAdKJy0AiOs2p8H24eEQIeWaVc89A4IWlTH/LHyxA6DF43SVpQKBgQDnKOH/gKAWnrCkL9Uv2WNqUqzuUYxgatyuGJ+FqkJ5MELp/4jnDaeYMesZ5xXkdJ1uSiMahl8eL5oT59gjkB9741E1u4EKCVC4bCYQJkXGR4ICjfyrTF2NfP79cgyE4wSDgrT6b0zq77vx8A5q+xYy+jS/8TcV1OqpxTGTAa9MhQKBgBNFeZNBIlifgYtYZYI2gKhiXq9Sjjq2FN4KOi8u2i5vYjQJ4Yg8SZFZUM9FTCFPb3RzMFoJrbo4eG+uZP+Tq/wKTBqkN7DsQhqFBHAIa5aMcq8ZSy/28AfWf+bhFKKhMyYANfK4ay4SCEFh3Ktv3lj+ujDWGrUxHC6QO9clAIAFAoGAafk/KqBwRA56UrsvFCGoRw0iBJvULDuxcgsNzvyQPvjWJGqm+64x4D86VgSv761aoz5Pu5BQuQj/rRKD70HafTRofaa5cL12iSXjiVHSeSU9QCiR5oI6/WuJhu2rOZzN6/CXQZyW+bnwQulX4sm7kqFMX5aZN2QGNNCXepqyH/UCgYAdpYwPDDX8FP2OrWxH6zuHMWX8NUCvbBMljKAF4CUNpEdX84s0gIWeauMsup9kOgJllk27xh8hZ0XfP1Igav2BsdCc2UW762Vr7SP6X4Xqtdqkt1Sq2XOxJP4Vndv5UA1LnYKNj3cu8felTIo9M5/f11ccVJ6agRlKI1pQI+oHGQ==
    -----END PRIVATE KEY-----
  auth-public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApe4ezQydGOmzZtDuDeENOKNpgO6e3N1ICF9/zWcqw9RTf/ZO/t44covZOjOmEk+/hQUifEGB844CDJ+stidI9+D0AXQz5aTkhgDDB4BO29KUYhlmIq4S0gfY9JOG+mohC0uROHtiZmJAxmSuawkGJivUECsnJINmvGmCO0/18wzbA0abdJ/lscxfALUOR0cZ02mMU60lzpd6N0IAzJsOrI7AWSx5q8JcIOZUWMDHostGz3e3VEE0tO0P4CktuP0mcRj0cxUknLmzIkXuNChFUhjC7TmgZyscCfT2iNSoecIBTAkQEh/EpUgi9j+LGtIstsy+qYEGxO65VrpcuMm6uQIDAQAB
    -----END PUBLIC KEY-----
  jwt-exp: 3600

  password-min-length: 6
  password-required-characters: ""
  site-url: https://385b-2610-150-3b21-0-216-3cff-fe09-e1be.ngrok-free.app
  one-time-expired-minutes: 5
  auth-providers:
    github:
      client-id: Iv23liJHJk6CCEs9PmFa
      client-secret: 04d6cfdb49cbe3119bbdd1e643a4ca98180706b4
      scopes:
        - user:email
    gitee:
      client-id: 23b803a4405cc613438532233c565d10be8c062f3ab2e1675665b255db83598f
      client-secret: 8f18b25f223102bd7ac059ffe4b9fe0f4c51bc7350027ddc9921019764ba5c07
      scopes:
        - emails
  redirect-urls:
    - http://*.baidu.com
  storage-update-signed-jwt-exp: 7200