spring:
  application:
    name: isupabase
  datasource:
    url: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?user=postgres.vxguqjxsufwgzhcnojsc&password=hOPnavWk3gZIOn6N
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategies.SnakeCaseStrategy
